const arrPlaces = [{
  'id': 346738648274,
  'name': "Przedszkole HappyDays",
  'polishName': "Przedszkole HappyDays",
  'primary': " ",
  'englishName': "Preschool HappyDays",
  'hasPerk': " ",
  'img': 'img/HappyDays.png',
  'location': {
    'address': "Krakowska, 89",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.761190,
    'lng': 20.800283,
    'postalCode': "25-705",
    'state': "Europe"
  },
  'site': "www.przedszkole.kielce.pl",
  'phone': "+48-535-953-935"
}, {
  'id': 34678648243,
  'name': "Pływalnia Delfin",
  'polishName': "Pływalnia Delfin",
  'primary': " ",
  'englishName': "Swimmingpool Delfin",
  'hasPerk': " ",
  'img': 'img/delfin.jpg',
  'location': {
    'address': " ul. Krakowska 2",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.865228,
    'lng': 20.626127,
    'postalCode': "25-029",
    'state': "Europe"
  },
  'site': "www.mosir.kielce.pl",
  'phone': "+48-41-366-90-13"
}, {
  'id': 436542343284,
  'name': "Kinoteatr Multikino",
  'polishName': "",
  'primary': " ",
  'englishName': "Cinema Multikino",
  'hasPerk': " ",
  'img': 'img/multikino.jpg',
  'location': {
    'address': "ul. Warszawska 26",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.865228,
    'lng': 20.626127,
    'postalCode': "25-312",
    'state': "Europe"
  },
  'site': "www.multikino.pl",
  'phone': "+48-41-248-64-10"
}, {
  'id': 233434250678,
  'name': "Wydział Matematyki Uniwersyteta imienia Jana Kochanowskiego",
  'polishName': "Wydział Matematyki Uniwersyteta imienia Jana Kochanowskiego",
  'primary': " ",
  'englishName': "Faculty of Mathematic UJK Kielce",
  'hasPerk': " ",
  'img': 'img/Wydział_Matematyczno-Przyrodniczy_UJK.jpg',
  'location': {
    'address': "ul. Świętokrzyska 15",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.865228,
    'lng': 20.626127,
    'postalCode': "25-406",
    'state': "Europe"
  },
  'site': "www.ujk.edu.pl/wmp",
  'phone': "+48-41-349-62-30"
}, {
  'id': 3425487834923,
  'name': "Homo Homini",
  'polishName': "Pomnik ofiarom terorryzmu",
  'primary': " ",
  'englishName': "Monument to victims of terrorism",
  'hasPerk': " ",
  'img': 'img/Kielce-Homo-Homini.jpg',
  'location': {
    'address': "ul. Księdza Piotra Ściegiennego",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.856156,
    'lng': 20.625007,
    'postalCode': "25-001",
    'state': "Europe"
  },
  'site': "www.um.kielce.pl",
  'phone': ""
}, {
  'id': 3428579255433,
  'name': "Pomnik ofiarom armii radzieckiej",
  'polishName': "Pomnik ofiarom armii radzieckiej",
  'primary': " ",
  'englishName': "Cementery of Soviet Soldiers",
  'hasPerk': " ",
  'img': 'img/cementry.jpg',
  'location': {
    'address': "",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.838175,
    'lng': 20.649444,
    'postalCode': "25-001",
    'state': "Europe"
  },
  'site': "www.um.kielce.pl",
  'phone': ""
}, {
  'id': 4234928742304,
  'name': "Wojewodzki Dom Kultury imienia Józefa Piłsudskiego",
  'polishName': "WDK",
  'primary': " ",
  'englishName': "Regional House of Culture",
  'hasPerk': " ",
  'img': 'img/multikino.jpg',
  'location': {
    'address': "ul. Księdza Piotra Ściegiennego, 2",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.863755,
    'lng': 20.626883,
    'postalCode': "25-033",
    'state': "Europe"
  },
  'site': "www.wdk-kielce.pl",
  'phone': "+48-41-365-51-00"
}, {
  'id': 342987593567425,
  'name': "Rezerwat przyrody 'Kadzielnia'",
  'polishName': "Rezerwat przyrody 'Kadzielnia",
  'primary': " ",
  'englishName': "Nature Reserve",
  'hasPerk': " ",
  'img': 'img/multikino.jpg',
  'location': {
    'address': "ul. Księdza Piotra Ściegiennego, 2",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.860912,
    'lng': 20.618288,
    'postalCode': "25-202",
    'state': "Europe"
  },
  'site': "www.amfiteatr-kadzielnia.pl",
  'phone': "+48-41-361-47-68"
}, {
  'id': 342987593567483,
  'name': "Wojewódzka Biblioteka Publiczna imienia Widolda Gombrowicza w Kielcach",
  'polishName': "Biblioteka Publiczna",
  'primary': " ",
  'englishName': "Public Library",
  'hasPerk': " ",
  'img': 'img/biblioteka.jpg',
  'location': {
    'address': "ul. Księdza Piotra Ściegiennego, 13",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.860912,
    'lng': 20.618288,
    'postalCode': "25-001",
    'state': "Europe"
  },
  'site': "www.wbp.kielce.pl",
  'phone': "+48-41-361-53-51"
}, {
  'id': '0236184354390',
  'name': "Park Miejski imienia Stanisława Staszica",
  'polishName': "Park Miejski",
  'primary': " ",
  'englishName': "City Park",
  'hasPerk': " ",
  'img': 'img/Staszica.jpg',
  'location': {
    'address': "ul. Jana Pawła II",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.868608,
    'lng': 20.624754,
    'postalCode': "25-960",
    'state': "Europe"
  },
  'site': "www.um.kielce.pl",
  'phone': "+48-41-361-53-51"
}, {
  'id': 342509852342,
  'name': "Liceum Ogólnokształcące imienia Stefana Żeromskiego. Muzeum",
  'polishName': "Liceum Żeromskiego",
  'primary': " ",
  'englishName': "City High School",
  'hasPerk': " ",
  'img': 'img/zeromski.jpg',
  'location': {
    'address': "ul. Jana Pawła II, 5",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.860912,
    'lng': 20.618288,
    'postalCode': "25-013",
    'state': "Europe"
  },
  'site': "zeromski.mnki.pl",
  'phone': "+48-41-344-57-92"
}, {
  'id': 34250985234422,
  'name': "Muzeum zabawek i zabawy",
  'polishName': "Muzeum zabawek i zabawy",
  'primary': " ",
  'englishName': "Museum of Toys",
  'hasPerk': " ",
  'img': 'img/zabawki.jpg',
  'location': {
    'address': "płac Wolności, 2",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.860912,
    'lng': 20.618288,
    'postalCode': "25-367",
    'state': "Europe"
  },
  'site': "muzeumzabawek.eu",
  'phone': "+48-41-343-37-06"
}, {
  'id': 323423098543,
  'name': "Narodowe Muzeum w Kielcach",
  'polishName': "Narodowe Muzeum w Kielcach",
  'primary': " ",
  'englishName': "The National Museum in Kielce",
  'hasPerk': " ",
  'img': 'img/muzeum_narodowe.jpg',
  'location': {
    'address': "płac Zamkowy, 1",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.860912,
    'lng': 20.618288,
    'postalCode': "25-001",
    'state': "Europe"
  },
  'site': "mnki.pl",
  'phone': "+48-41-344-40-14"
}, {
  'id': 324298752340,
  'name': "Muzeum Wsi Kieleckiej",
  'polishName': "Muzeum Wsi Kieleckiej",
  'primary': " ",
  'englishName': "Kielce Region Countryside Museum",
  'hasPerk': " ",
  'img': 'img/wies.jpg',
  'location': {
    'address': "ul. Jana Pawła II, 6",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.867977,
    'lng': 20.628877,
    'postalCode': "25-025",
    'state': "Europe"
  },
  'site': "mwk.com.pl",
  'phone': "+48-41-344-40-14"
}, {
  'id': 732430956723,
  'name': "Muzeum Historii Kielc",
  'polishName': "",
  'primary': " ",
  'englishName': "Museum of History",
  'hasPerk': " ",
  'img': 'img/wies.jpg',
  'location': {
    'address': "ul. Świętego Leonarda, 4",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.869991,
    'lng': 20.634731,
    'postalCode': "25-303",
    'state': "Europe"
  },
  'site': "mhki.kielce.eu",
  'phone': "+48-41-340-55-20"
}, {
  'id': 732430956715,
  'name': "Pałac Tomasza Zielińskiego",
  'polishName': "Pałac Tomasza Zielińskiego",
  'primary': " ",
  'englishName': "Zieliński Palace",
  'hasPerk': " ",
  'img': 'img/Tomasza-Zielinskiego.jpg',
  'location': {
    'address': "ul. Zamkowa, 5",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.869991,
    'lng': 20.634731,
    'postalCode': "25-009",
    'state': "Europe"
  },
  'site': "palacykzielinskiego.pl",
  'phone': "+48-41-367-67-70"
}, {
  'id': 32343205347,
  'name': "Pomnik Pamięci Kieleckiego Getta",
  'polishName': "Getto",
  'primary': " ",
  'englishName': "Monument for Victims of Ghetto",
  'hasPerk': " ",
  'img': 'img/getto.jpg',
  'location': {
    'address': "al. IX Wieków Kielc, 3",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.875083,
    'lng': 20.627933,
    'postalCode': "25-001",
    'state': "Europe"
  },
  'site': "",
  'phone': ""
}, {
  'id': 32432420545,
  'name': "Świętokrzyski Urząd Wojewódski w Kielcach",
  'polishName': "Urząd Wojewódzki",
  'primary': " ",
  'englishName': "Świętokrzyski Provincial Office in Kielce",
  'hasPerk': " ",
  'img': 'img/urząd.jpg',
  'location': {
    'address': "al. IX Wieków Kielc, 3",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.875983,
    'lng': 20.630686,
    'postalCode': "25-001",
    'state': "Europe"
  },
  'site': "kielce.uw.gov.pl",
  'phone': "+48-41-342-14-13"
}, {
  'id': 342342564738,
  'name': "Politechnika Świętokrzyska",
  'polishName': "Politechnika Świętokrzyska",
  'primary': " ",
  'englishName': "Technical University in Kielce",
  'hasPerk': " ",
  'img': 'img/Politechnika.jpg',
  'location': {
    'address': "aleja Tysiąclecia Państwa Polskiego 7",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.879109,
    'lng': 20.640077,
    'postalCode': "25-314",
    'state': "Europe"
  },
  'site': "tu.kielce.pl",
  'phone': "+48-41-342-14-13"
}, {
  'id': 324545290567,
  'name': "Kielecki Teatr Tańca",
  'polishName': "Kielecki Teatr Tańca",
  'primary': " ",
  'englishName': "Kielce Dance Canter",
  'hasPerk': " ",
  'img': 'img/teatr_tanca.jpg',
  'location': {
    'address': "plac Moniuszki 2B",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.869014,
    'lng': 20.636823,
    'postalCode': "25-334",
    'state': "Europe"
  },
  'site': "ktt.pl",
  'phone': "+48-41-367-67-12"
}, {
  'id': 343243758943,
  'name': "Fitness Club Tao",
  'polishName': "Fitness Club Tao",
  'primary': " ",
  'englishName': "Fitness Club Tao",
  'hasPerk': " ",
  'img': 'img/tao.jpg',
  'location': {
    'address': "ul. Jagiellońska 62,",
    'city': "Kielce",
    'cc': "Polish",
    'country': "Rzeczpospolita Polska",
    'formattedAddress': " ",
    'labelLedLatLing': " ",
    'lat': 50.875625,
    'lng': 20.607615,
    'postalCode': "25-734",
    'state': "Europe"
  },
  'site': "fitnessclubtao.pl",
  'phone': "+48-664-266-909"
}
];

export default arrPlaces;